# Generated by Django 5.0.7 on 2024-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_filerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerequest',
            name='description',
        ),
        migrations.AddField(
            model_name='filerequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
